image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ngosang/amule
  tag: 2.3.3-19@sha256:172bc19dbe72ab35149781aaf268f204bb0663716b2619917a3d15e65b0900bd
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4711
        protocol: http
        targetPort: 4711
  porttcp:
    enabled: true
    ports:
      porttcp:
        enabled: true
        port: 4662
        protocol: tcp
        targetPort: 4662
  portudp:
    enabled: true
    ports:
      portudp:
        enabled: true
        port: 4672
        protocol: udp
        targetPort: 4672
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            WEBUI_PWD: ""
            WEBUI_TEMPLATE: default
persistence:
  complete:
    enabled: true
    mountPath: /incoming
  config:
    enabled: true
    mountPath: /home/amule/.aMule
  incomplete:
    enabled: true
    mountPath: /temp
portal:
  open:
    enabled: true
