image:
  repository: ghcr.io/linuxserver/ombi
  pullPolicy: IfNotPresent
  tag: 4.47.1@sha256:66980d7a7e8b0442e9d86be0dad0ee7f20b89e34080d1fee37f160fbda020737
service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579
persistence:
  config:
    enabled: true
    mountPath: "/config"
# Enabled mariadb
# ... for more options see https://github.com/tccr.io/truecharts/charts/tree/master/tccr.io/truecharts/mariadb
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: ombi
    username: ombi
    password: ombi
  primary:
    persistence:
      enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
